# Generated by Django 5.2.11 on 2026-03-02 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oportunidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('valor_estimado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.CharField(choices=[('Nuevo', 'Nuevo'), ('Contactado', 'Contactado'), ('En negociación', 'En negociación'), ('En seguimiento', 'En seguimiento'), ('Cerrado', 'Cerrado')], default='Nuevo', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oportunidades', to='clientes.cliente')),
            ],
        ),
    ]
